# Generated by Django 4.0.3 on 2022-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_topic_1_3_topic_1_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_1_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_1_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
