# Generated by Django 4.0.3 on 2022-04-27 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_topic_1_5_topic_1_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_1_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='')),
                ('year', models.IntegerField(null=True, verbose_name='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.topic_1_6', verbose_name='対象科目')),
            ],
        ),
        migrations.CreateModel(
            name='Class_1_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='')),
                ('year', models.IntegerField(null=True, verbose_name='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.topic_1_5', verbose_name='対象科目')),
            ],
        ),
        migrations.CreateModel(
            name='Class_1_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='')),
                ('year', models.IntegerField(null=True, verbose_name='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.topic_1_4', verbose_name='対象科目')),
            ],
        ),
        migrations.CreateModel(
            name='Class_1_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='')),
                ('year', models.IntegerField(null=True, verbose_name='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.topic_1_3', verbose_name='対象科目')),
            ],
        ),
        migrations.CreateModel(
            name='Class_1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='')),
                ('year', models.IntegerField(null=True, verbose_name='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.topic_1_2', verbose_name='対象科目')),
            ],
        ),
        migrations.CreateModel(
            name='Class_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='')),
                ('year', models.IntegerField(null=True, verbose_name='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.topic_1_1', verbose_name='対象科目')),
            ],
        ),
    ]
